### ISSUE TITLE
Documentation on options

### ISSUE THREAD

**Issue by jansipke** [sgratzl/chartjs-chart-wordcloud#10]
In the documentation there is a basic example of the wordcloud plugin. What's missing for me is an explanation of how to use the options. For example, how can the colors and orientation of the words be changed? The supplied link to the source is not enough for me to see how the options parameter should be filled.

**Comment by mklasen** [comment]
This is some of the options I found whlle trying to make the words clickable. (not all working)

```
	const ctx = document.getElementById('canvas')
	const ctxP = ctx.getContext('2d');
	window.chart = new Chart(ctxP, {
		type: 'wordCloud',
		data: data,
		options: {
			title: {
				display: false,
				text: 'Chart.js Word Cloud',
			},
			color: "green",
			family: "'Helvetica Neue', 'Helvetica', 'Arial', sans-serif",
			hoverColor: "red",
			lineHeight: 100,
			maxRotation: 0,
			minRotation: -90,
			padding: 1,
			rotate: 45,
			rotationSteps: 5,
			size: 90,
			string: "normal normal 90px 'Helvetica Neue', 'Helvetica', 'Arial', sans-serif",
			style: "normal",
			weight: "bold",
			plugins: {
				legend: {
					display: false,
				},
			},
		},
	});
	ctx.onclick = function(evt) {
		var points = window.chart.getElementsAtEventForMode(evt, 'nearest', {
			intersect: true
		}, true);
		console.log(points);
	}
```

**Comment by jansipke** [comment]
Thanks for replying @mklasen. I tested a few of these options: 'rotate' seems to do nothing, but the 'color' does work, can be either a string or an array of colors, and 'minRotation' / 'maxRotation' also work.
