### ISSUE TITLE
How to use hoverStyle

### ISSUE THREAD

**Issue by Paul-Hume** [sgratzl/chartjs-chart-wordcloud#12]
In your documentation you point to a part in your file where hoverStyle take a string. 

```
export interface IWordElementHoverOptions {
  hoverColor: string;
  hoverSize: number;
  hoverStyle: string;
  hoverWeight: string;
}
```

I can't see anywhere where you give an example of what this string should look like or include. I'm trying to change the cursor to a pointer on hover over the word. 

What string is `hoverStyle` expecting? is it possible to show a pointer when hovering over the words?

**Comment by sgratzl** [comment]
see also #13 to fix resolving options.

> hoverStyle
it is the font style as in `'normal' | 'italic' | 'oblique'`

> is it possible to show a pointer when hovering over the words?

not using any options, since chart.js is a canvas based solution, you have to listen the onHover event of chart.js and manually set the cursor style of the DOM element
