### ISSUE TITLE
WordCloud and Venn Charts in ChartJs 2.9.X versions or 2.X versions?

### ISSUE THREAD

**Issue by skowsikaxl** [sgratzl/chartjs-chart-wordcloud#19]
I am great fan of your work. My question, is there a way to make Venn and WordCloud plugins work in 2.X versions of Chart.Js. Preferably last stable version 2.9.4 of Chart.Js 2?

**Comment by sgratzl** [comment]
no, both plugins were developed when chart.js 3 was already in an alpha version and I don't intend without help to backport these plugins. Happy to review any PR that does the backport
