### ISSUE TITLE
core.js:6241 ERROR Error: "linear" is not a registered scale.

### ISSUE THREAD

**Issue by soislom** [sgratzl/chartjs-chart-wordcloud#4]
I'm having the following question
When I try to run the test code, there is a error with chrome

**Screenshots / Sketches**
![98C602B1-B072-4998-A3E3-8B84D217577D](https://user-images.githubusercontent.com/27555834/99754355-318b6200-2b23-11eb-9541-699c67b91dea.png)

**Context**
this is my test code .
![266D439C-1EAB-44be-87CE-42D2ADB82EA1](https://user-images.githubusercontent.com/27555834/99754377-3bad6080-2b23-11eb-9e0f-a2206cfb1bd2.png)
![6A9A3937-4EBC-40fb-8E61-ED9621E35A6D](https://user-images.githubusercontent.com/27555834/99754382-3e0fba80-2b23-11eb-85a0-6d3c972a62e0.png)

- Version:
![2E850FD1-43AA-4635-84E1-5735EF7F1613](https://user-images.githubusercontent.com/27555834/99754392-449e3200-2b23-11eb-8a8d-24e764d85c73.png)

- Browser:
chrome
**Additional context**

**Comment by sgratzl** [comment]
chart.js 3 is ESM tree shakeable and requires to register all components that you are going to use. Thus, you have to register the linear scale manually

**Comment by sgratzl** [comment]
see also https://www.chartjs.org/docs/next/getting-started/integration#bundlers-webpack-rollup-etc

**Comment by DakshMiglani** [comment]
Registered it and still getting an error @sgratzl 

![image](https://user-images.githubusercontent.com/23355449/101534904-d3cd9580-39bd-11eb-8044-259e6f0e994e.png)

**Comment by ryanlogsdon** [comment]
Add these lines to your myPage.component.ts file:

```
import { Chart, registerables } from 'chart.js';
Chart.register(...registerables);
```


`https://www.chartjs.org/docs/next/getting-started/integration.html`

**Comment by AndrePriedols** [comment]
ryanlogsdon, you saved my day! Lost a few hours trying to figure this out. Thanks!

**Comment by parzibyte** [comment]
I followed @ryanlogsdon comment and it worked, thanks!. Just add this line: 
`import Chart from 'chart.js/auto';`
And everything will work just fine

**Comment by mrjhonyvidal** [comment]
> Add these lines to your myPage.component.ts file:
> 
> ```
> import { Chart, registerables } from 'chart.js';
> Chart.register(...registerables);
> ```
> 
> `https://www.chartjs.org/docs/next/getting-started/integration.html`

Heroe!

**Comment by yash-deore** [comment]
> I followed @ryanlogsdon comment and it worked, thanks!. Just add this line:
> `import Chart from 'chart.js/auto';`
> And everything will work just fine

Thanks a lot 😀😀😀

**Comment by atilamagalhaes4** [comment]
> Add these lines to your myPage.component.ts file:
> 
> ```
> import { Chart, registerables } from 'chart.js';
> Chart.register(...registerables);
> ```
> 
> `https://www.chartjs.org/docs/next/getting-started/integration.html`
> 
> I'm really glad this code is helping! I've made a walk-through video on Angular + Firebase + Chart.js. I hope it can help, too [https://www.youtube.com/watch?v=PY4yjjcThos&ab_channel=D-I-Ry](url)

That worked for me. Thanks!

**Comment by thebest2019** [comment]
Your

> Add these lines to your myPage.component.ts file:
> 
> ```
> import { Chart, registerables } from 'chart.js';
> Chart.register(...registerables);
> ```
> 
> `https://www.chartjs.org/docs/next/getting-started/integration.html`


You're hero man.

**Comment by riverandeye** [comment]
@ryanlogsdon Thank you for sure

**Comment by exjade** [comment]
> Add these lines to your myPage.component.ts file:
> 
> ```
> import { Chart, registerables } from 'chart.js';
> Chart.register(...registerables);
> ```
> 
> `https://www.chartjs.org/docs/next/getting-started/integration.html`
> 
> I'm really glad this code is helping! I've made a walk-through video on Angular + Firebase + Chart.js. I hope it can help, too [https://www.youtube.com/watch?v=PY4yjjcThos&ab_channel=D-I-Ry](url)

Thank you!

**Comment by truong2307** [comment]
> Add these lines to your myPage.component.ts file:
> 
> ```
> import { Chart, registerables } from 'chart.js';
> Chart.register(...registerables);
> ```
> 
> `https://www.chartjs.org/docs/next/getting-started/integration.html`
> 
> I'm really glad this code is helping! I've made a walk-through video on Angular + Firebase + Chart.js. I hope it can help, too [https://www.youtube.com/watch?v=PY4yjjcThos&ab_channel=D-I-Ry](url)

WOW, Thank you

**Comment by scil** [comment]
only import linear scale and some common objects:
```
import { Chart as ChartJS, Title, Tooltip, Legend, BarElement, CategoryScale, LinearScale, } from 'chart.js'

ChartJS.register(Title, Tooltip, Legend, BarElement, CategoryScale, LinearScale, )

```

**Comment by navinrangar** [comment]
> Add these lines to your myPage.component.ts file:
> 
> ```
> import { Chart, registerables } from 'chart.js';
> Chart.register(...registerables);
> ```
> 
> `https://www.chartjs.org/docs/next/getting-started/integration.html`
> 
> I'm really glad this code is helping! I've made a walk-through video on Angular + Firebase + Chart.js. I hope it can help, too [https://www.youtube.com/watch?v=PY4yjjcThos&ab_channel=D-I-Ry](url)

thanks man

**Comment by davappler** [comment]
This worked for me thanks a lot 🚀
```
import { Chart, registerables } from 'chart.js';
Chart.register(...registerables);
```

**Comment by Mattiullah134** [comment]
This worked for me thanks a lot 🚀

import { Chart, registerables } from 'chart.js';
Chart.register(...registerables);

**Comment by yashj0511** [comment]
@ryanlogsdon Thanks

**Comment by zongyanglaobiao** [comment]
> 将这些行添加到您的 myPage.component.ts 文件中：
> 
> ```
> import { Chart, registerables } from 'chart.js';
> Chart.register(...registerables);
> ```
> 
> `https://www.chartjs.org/docs/next/getting-started/integration.html`
> 
> 我真的很高兴这段代码有帮助！我制作了有关 Angular + Firebase + Chart.js 的演练视频。我希望它也能有所帮助[https://www.youtube.com/watch?v=PY4yjjcThos&ab_channel=DI-Ry](url)

thinks , you reply for me help

**Comment by padupe** [comment]
`v4.4.3`
I tried what @ryanlogsdon  indicated, but I still get the error. :(

**Comment by 0xadri** [comment]
> `v4.4.3` I tried what [@ryanlogsdon](https://github.com/ryanlogsdon) indicated, but I still get the error. :(

Try instead:

`import Chart from 'chart.js/auto'`

More on https://stackoverflow.com/questions/65002923/chart-js-where-do-i-find-which-components-should-be-registered
