### ISSUE TITLE
Tooltip feature is a native feature of the library ?

### ISSUE THREAD

**Issue by BlackWolf00** [sgratzl/chartjs-chart-wordcloud#43]
Is the tooltip function you use in the CodePen demo a native feature of the library?

![Screenshot (250)](https://github.com/sgratzl/chartjs-chart-wordcloud/assets/56046546/617ddf23-ce2c-47b7-bea8-b40bd8363e06)

**Comment by sgratzl** [comment]
this repo is a plugin for chart.js which is providing the tooltip. take a look at their documentation

**Comment by BlackWolf00** [comment]
Thank you for the info!
