### ISSUE TITLE
Page freezes on init

### ISSUE THREAD

**Issue by supmanyu** [sgratzl/chartjs-chart-wordcloud#5]
On initialising and creating the chart instance, the webpage freezes, and has to be force closed

**To Reproduce**

1. Happening only on production

**Expected behavior**

Wordcloud should initialize and render

**Screenshots**

**Context**

- Version: v3.0.0_Beta-7
- Browser: Any

**Additional context**

**Comment by sgratzl** [comment]
creating a word cloud is quite computationally intense. How many words are you trying to layout?

**Comment by supmanyu** [comment]
I was using the codepen example directly, also have some other charts on the page which are initialized on page load, but the wordcloud was initiated on a button click, could it be because of other charts present in the DOM?

**Comment by sgratzl** [comment]
without an example I can play with it is difficult to know what is going on or why the browser is so busy

**Comment by supmanyu** [comment]
I agree, but the issue is only apparent on this website that i'm working on at my job, which i cant share with you since it requires users to login for obvious reasons, and the library works fine on codepen, albeit with a bit of a delay in rendering, but that is expected since you already pointed out that there is a performance hit while rendering anyways. I've switched to wordcloud2.js for now, since the functionality required is only visual, and not much interaction is going to take place. Thanks for the response, i'm closing this issue since i cant produce a working example in isolation.
