### ISSUE TITLE
packing density / auto-scaling?

### ISSUE THREAD

**Issue by Offbeatmammal** [sgratzl/chartjs-chart-wordcloud#52]
I've noticed quite a few of the clouds that I have generated are fairly sparse compared to the samples (see eg below).

Do you have any recommendations to either force it to try a few more passes for better fitment, and/or suggestions to adjust the pixel scales in the data to optimally fill the available space?

It seems that it likes to rotate things when perhaps different rotations would fit the layout/space better?

<img width="517" alt="image" src="https://github.com/sgratzl/chartjs-chart-wordcloud/assets/677594/44de1887-33aa-405c-9f0c-b25dc737baf6">

**Comment by sgratzl** [comment]
seems like it has more than enough space for your words. Thus, this layout appears.  You could increase the overall font-size, ie scale the value for each element by a certain factor or use the element options to restrict rotations (https://www.sgratzl.com/chartjs-chart-wordcloud/api/interfaces/interface.IWordElementOptions.html)

**Comment by Offbeatmammal** [comment]
thanks, I can add some options to the UI where I'm using this to let folks apply scaling and turn rotation on/off (had hoped I was just missing a magic option to automatically optimize for a denser layout kinda like Tableau does for us, adding options for some of my users sometimes causes more trouble than it's worth!)
