### ISSUE TITLE
Can I make sure all words always fit into canvas?

### ISSUE THREAD

**Issue by sergotail** [sgratzl/chartjs-chart-wordcloud#7]
I use word clouds with some data i can't make any assumption on its weigths distribution. It's also i don't know min and max possible weights and can only assume weights scale, for example, logarithmic. But as i understood, i have to scale weights myself before feeding data into word cloud chart.
Like with line charts, scale may be changed automatically that so all the data fit on canvas. Is there some way to achieve similar behaviour in word cloud chart?

Thanks for response!

**Comment by sgratzl** [comment]
this plugin is based on https://github.com/jasondavies/d3-cloud thus it inherit all its features but also limitations. Arranging word clouds is tricky in general. There is the fit option (enabled by default) which scales the word cloud to fit in the chart.js canvas. However, it cannot be guaranteed. 

see also which is a logic to place all the words in multiple tries:

https://github.com/sgratzl/chartjs-chart-wordcloud/blob/d1c972448ddde965494785a7553d5e5b8eef7065/src/controllers/WordCloudController.ts#L142-L150

**Comment by sergotail** [comment]
Thank you for info!
