### ISSUE TITLE
make tries/factor on resize a user controlled option

### ISSUE THREAD

**Issue by Offbeatmammal** [sgratzl/chartjs-chart-wordcloud#70]
in the WordCloudController there is some code to control scaling of the wordcloud:
https://github.com/sgratzl/chartjs-chart-wordcloud/blob/d1c972448ddde965494785a7553d5e5b8eef7065/src/controllers/WordCloudController.ts#L142-L150
is it possible to make the tries, and factor, options that can be passed from the users code?
(going to try and find some time to explore the logic, but not tried editing/building one of these plug-ins yet)

alternatively, is it possible to guestimate a better initial factor based on the difference between the initial pass and the available space (I’ve tried following the maths but couldn’t see an obvious answer to this!)

at the moment, I can’t see a way in the instanciating code to know that it had a problem with fitting all the elements so can’t (eg) manually scale the values myself and try again.

**Comment by sgratzl** [comment]
re guessestimate, it is challenging since with a different size the layout changes also from the already positioned words. So I don't really know how much space is missing. 

let me check how to expose a more configurable way for this autofit mechanism.

**Comment by Offbeatmammal** [comment]
thanks! just saw the npm version update.
is the correct way to access these new params:
`options: {
     padding: 10,
     fit: true,
     rotate: 0, rotationSteps:0,
     growOptions: {maxTries: 5, scalingFactor: 1.3},
...`

I guess the message
https://github.com/sgratzl/chartjs-chart-wordcloud/blob/b975f5d51e7033b6fa49a712347507b27852da20/src/controllers/WordCloudController.ts#L164-L166
probably needs tweaking now too ;)

**Comment by sgratzl** [comment]
e.g.

![image](https://github.com/sgratzl/chartjs-chart-wordcloud/assets/4129778/fb033ab2-8731-4c1b-91e6-2644c34a3e66)
