### ISSUE TITLE
fit:true seems not to be the default - am I confused?

### ISSUE THREAD

**Issue by Offbeatmammal** [sgratzl/chartjs-chart-wordcloud#71]
looking at the code
https://github.com/sgratzl/chartjs-chart-wordcloud/blob/d1c972448ddde965494785a7553d5e5b8eef7065/src/controllers/WordCloudController.ts#L200-L204
it implies this will be defaulting to true, but when I instanciate a wordcloud without explicility including `fit: true` in the options, it seems to behave the same as if it was false.

not sure if I’m missing something obvious (quite likely!) or if this is an easy fix?

**Comment by sgratzl** [comment]
you are right, the default value doesn't seem to be applied. for backwards compatibility it will change just the documentation that it is default = false to avoid breaking everyone's code.

**Comment by Offbeatmammal** [comment]
thanks!
