### ISSUE TITLE
Are multi-line "words" possible?

### ISSUE THREAD

**Issue by Offbeatmammal** [sgratzl/chartjs-chart-wordcloud#72]
I'm working on something at the moment where I'd like to include some secondary information with the word in the word cloud...

for example, the "word" could be the name of a country, but I want on a second line (ideally in a smaller font, perhaps different color etc, and in an idea world an option to set the minimum font/pixel size for the second line at which point it disappears) the population (or gender breakdown, or other ... user can toggle what's displayed)

I've been experimenting, both with the existing code and trying to kludge something together with DataLabel overlays, but not had any luck getting something viable.

I realize it's a very niche, but maybe someone has solved the problem before

**Comment by sgratzl** [comment]
they are currently not supported. this plugin uses https://github.com/jasondavies/d3-cloud under the hood and thus is bound by its limitations

**Comment by Offbeatmammal** [comment]
ah, thanks for the upstream pointer. will see if there's anything possible there.
