### ISSUE TITLE
Windows vs macOS / iOS rendering

### ISSUE THREAD

**Issue by Offbeatmammal** [sgratzl/chartjs-chart-wordcloud#73]
using the example at https://www.sgratzl.com/chartjs-chart-wordcloud/examples/

on PC I get no overlap:
<img width="242" alt="image" src="https://github.com/sgratzl/chartjs-chart-wordcloud/assets/677594/59ce544f-709d-45b7-9f98-d807e16b7828">

same test on macOS (Safari, Chrome) and iOS (Safari) the words overlap:
<img width="201" alt="image" src="https://github.com/sgratzl/chartjs-chart-wordcloud/assets/677594/34fe759b-1e4b-42d0-98ea-75ce62bdb123">

is there anything I should be passing in when I instantiate the chart to help it cope with platform differences?

**Comment by sgratzl** [comment]
my guess the different systems have different DPIs in addition there is some randomness going on when it comes to rotation, so each time you run it without fixing the random seed it might result in a different result.

**Comment by sgratzl** [comment]
I would look at https://www.chartjs.org/docs/latest/configuration/device-pixel-ratio.html
