### ISSUE TITLE
borders and background colors?

### ISSUE THREAD

**Issue by Offbeatmammal** [sgratzl/chartjs-chart-wordcloud#74]
is it possible to specify borders/background colors for the words - either within WordCloud instantiation or using existing ChartJS callbacks to get the dimensions and position of each word?

would be handy to help differentiate the words when there's a cluster of similar sized/colored words (and a handy extension if [multi-line words](#72) are also possible)

**Comment by sgratzl** [comment]
see also 

https://github.com/sgratzl/chartjs-chart-wordcloud/blob/a8725a363c040e6859da784e9a25056e1644942f/src/elements/WordElement.ts#L4-L41

for available styling options

**Comment by Offbeatmammal** [comment]
thanks - probably didn't explain myself that well. rather than the stroke (which is handy for sure) I was thinking about a rectangle behind the word itself (in the context of multiline, would explicity join the two lines as a single block) but doesn't look like it's super easy

**Comment by sgratzl** [comment]
there is no native support for it. You would have to override the `draw` method of the WorldElement, 

see https://github.com/sgratzl/chartjs-chart-wordcloud/blob/main/src/elements/WordElement.ts#L172

However, there is no promise with respect to ordering, so it can be that a smaller contained word is drawn before a bigger one, so the background would hide it
