### ISSUE TITLE
React implementation

### ISSUE THREAD

**Issue by alvaroserrrano** [sgratzl/chartjs-chart-wordcloud#8]
I'm having the following question. How can this be included in a React project as a <WordsCloud /> component.
My problem is basically understanding how could I access the ctx (document.getElementById) from a React functional component. It is returning me null.

**Screenshots / Sketches**

This is my WordsCloud.js file for reference. 
```
const data = {
    labels: initialWords.map((d) => d.key),
    datasets: [
      {
        label: '',
        data: initialWords.map((d) => 10 + d.value * 10),
      },
    ],
  };
  const options = {
    title: {
      display: true,
      text: 'Chart.js Word Cloud',
    },
  };
  const ctx = document.getElementById('cloudmap').getContext('2d');
  const chart = new WordCloudChart(ctx, {
    data,
    options,
  });
  return (
    <div>
      <div>
        <canvas id='cloudmap'></canvas>
      </div>
      <chart />
    </div>
  );
```
**Context**

- Version:
- Browser:

**Additional context**

**Comment by sgratzl** [comment]
this is a plugin for chart.js. have you looked up React wrappers for chart.js such as https://github.com/jerairrest/react-chartjs-2

**Comment by wholebuzz** [comment]
A sample using React would be excellent.  I'm using `react-chartjs-2` successfully for Line chart.  But it's not clear to me how to use with `chartjs-chart-wordcloud`.

**Comment by wholebuzz** [comment]
To answer my question:
```
import { Chart } from 'react-chartjs-2'
import { WordCloudController, WordElement } from 'chartjs-chart-wordcloud'
const RectChartJs = require('react-chartjs-2') // Strange default import issues otherwise

export function MyComponent() {
  const chartRef = useRef(null)
  if (!chartRef.current) Chart.register(WordCloudController, WordElement)
  return (
    <RectChartJs.default width="500" height="500" type="wordCloud" ref={chartRef} data={data} options={{}} />
  )
}
```
